### ISSUE TITLE
Compatibility with ROS melodic

### ISSUE THREAD

**Issue by JeremieBourque1** [deltarobotone/visy_neopixel_pkg#2]
Hi, I tried using this package and launcing `neopixel.launch` but when I do so, I get the following error:
```
Traceback (most recent call last):
  File "/home/jeremie/catkin_ws/src/visy_neopixel_pkg/scripts/visy_neopixel_pkg/neo_pixel_node.py", line 4, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
```

I then noticed that the neopixel node was made with python 3, but since I am using ROS melodic I am forced to use python 2. Is there a way to make it work in my case?

Thank you

**Comment by buerger-pascal** [comment]
Hi, i tested this package with kinetic and melodic. You can run the nodes using python 3 at kinetic and melodic. I know kinetic and melodic are build with python 2 but it is possible to use python 3 if you don't need specific python 2 libraries. Did you modify the first line to python 2 at neo_pixel_node? The neopixel driver libraries are only available at python 3. That's why i used python 3.

If you leave the nodes as they are they should work. Don't forget to install required libraries like in the action.yml:  sudo apt-get install python3-setuptools && sudo pip3 install rpi_ws281x adafruit-circuitpython-neopixel

**Comment by buerger-pascal** [comment]
Additionally you need to install following packages to get python 3 nodes working with melodic: sudo apt-get install python3-pip python3-all-dev python3-rospkg python3-rospy

**Comment by JeremieBourque1** [comment]
Thank you
